random_seed: 74
run_name: lds_hybrid_200
save_dir: outputs/april9/
input_length: [0]
max_length: [32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072] # total length of output
temperature: 1
top_k: 1
repeat: 3
cache: true
debug: false
lds_state_dim: 200