random_seed: 74
run_name: lds_hybrid_800
save_dir: outputs/april9/
input_length: [0]
max_length: [262144] # total length of output
temperature: 1
top_k: 1
repeat: 3
cache: true
debug: false
lds_state_dim: 800